name: CI/CD Pipeline for WiseCow App

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: madhav1110/wisecoweb
  IMAGE_TAG: latest

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

  deploy:
    name: Deploy to Kubernetes (via Minikube)
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
        # optional config, you can adjust driver, memory, kubernetes-version etc
        driver: docker
        memory: 2048m
        cpus: 2
        kubernetes-version: stable

    - name: Use Minikube’s Docker daemon
      run: |
        # Let subsequent docker and kubectl commands talk to Minikube’s docker
        eval $(minikube --profile minikube docker-env)

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false

    - name: Verify Deployment Status
      run: |
        kubectl rollout status deployment/wisecow-deployment
        kubectl get pods
        kubectl get svc
